### ISSUE TITLE
Every minute a log entry of "INFO GelfTcpTransport: Channel disconnected!" is written to logs

### ISSUE THREAD

**Issue by NathanChristie** [Graylog2/log4j2-gelf#11]
We are able to successfully configure applications with a Gel appender and verify the proper transmission of those messages to Graylog. However, every minute in our logs the message:
"INFO GelfTcpTransport: Channel disconnected!" is displayed. This is a little unreasonable across multiple apps to have this message spamming our logs every minute.

Is there any configuration we can tweak to lower the level of this message?

**Comment by NathanChristie** [comment]
As a workaround (if you're using log4j2), you can change the message level of the noisy class by adding the following logger into your log42j.xml:

```
    <!-- Prevent spamming "INFO GelfTcpTransport: Channel disconnected!" when a channel goes inactive -->
    <Logger name="org.graylog2.gelfclient.transport.GelfTcpTransport" level="error" additivity="false">
        <appender-ref ref="YourGelfAppenderName" />
        <appender-ref ref="YourOtherLogAppenderName" />
```

As of this posting, the only INFO-level message in this class IS that warning, so changing it to WARN is fairly low impact.

**Comment by joschi** [comment]
@NathanChristie Thanks for posting the Log4j 2 configuration.

I'll close this issue as it's not directly to that log message in [gelfclient](https://github.com/Graylog2/gelfclient).
