### ISSUE TITLE
Appenders contains an invalid element or attribute "GELF"

### ISSUE THREAD

**Issue by delfer** [Graylog2/log4j2-gelf#13]
My project is with Ant. log4j2-gelf library from [central.maven.org](http://central.maven.org/maven2/org/graylog2/log4j2/log4j2-gelf/1.1.0/log4j2-gelf-1.1.0.jar)
Log4j v. 2.4.1

log4j2.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="ALL" packages="org.graylog2.log4j2">
    <Appenders>

        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{dd.MM.yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>

        <GELF name="GELFAppender" server="192.168.0.17" port="12201" hostName="ddocserver">
        </GELF>

    </Appenders>
    <Loggers>

        <Logger name="testlogger" additivity="false" level="all">
            <AppenderRef ref="Console"/>
        </Logger>

        <Root level="warn">
            <AppenderRef ref="Console"/>
            <AppenderRef ref="GELFAppender"/>
        </Root>
    </Loggers>
</Configuration>
```

Debug output:

```
...
DEBUG Took 0,000498 seconds to load 0 plugins from package org.graylog2.log4j2
...
ERROR Appenders contains an invalid element or attribute "GELF"
...
ERROR Unable to locate appender "GELFAppender" for logger config "root"
```

**Comment by joschi** [comment]
Please ensure that the log4j2-gelf JAR file _and its dependencies_ are in the classpath of your application.

**Comment by delfer** [comment]
log4j2-gelf depends on:
- log4j-core 2.1
- gelfclient 1.3.0

I have:
- log4j-core-2.4.1.jar
- gelfclient-1.3.0.jar

Do I need to use log4j 2.1 insted of 2.4.1?

**Comment by joschi** [comment]
As long as Log4j 2.4.1 didn't break backwards compatibility, those should be fine. Instead of pulling each dependency manually, you could also just use the shaded version of log4j2-gelf which includes all relevant classes: http://central.maven.org/maven2/org/graylog2/log4j2/log4j2-gelf/1.1.0/log4j2-gelf-1.1.0-shaded.jar

BTW, log4j2-gelf doesn't depend on `log4j-slf4j-impl`. That's only a test dependency and not required at runtime.

**Comment by delfer** [comment]
I have the same output with shared library. I also try to buld 1.1.1 from repo - same story.

**Comment by joschi** [comment]
I can't reproduce your problem: https://github.com/joschi/log4j2-gelf-issue-13

Make sure that all required dependencies are on the classpath. The following line in your logs hint to something missing:

```
DEBUG Took 0,000498 seconds to load 0 plugins from package org.graylog2.log4j2
```

The following output is from my working demo (see repository mentioned above):

```
2015-11-26 11:45:04,258 main DEBUG Took 0,002833 seconds to load 1 plugins from package org.graylog2.log4j2
[...]
2015-11-26 11:45:04,302 main DEBUG Building Plugin[name=appender, class=org.graylog2.log4j2.GelfAppender]. Searching for builder factory method...
2015-11-26 11:45:04,303 main DEBUG No builder factory method found in class org.graylog2.log4j2.GelfAppender. Going to try finding a factory method instead.
2015-11-26 11:45:04,303 main DEBUG Still building Plugin[name=appender, class=org.graylog2.log4j2.GelfAppender]. Searching for factory method...
2015-11-26 11:45:04,304 main DEBUG Found factory method [createGelfAppender]: public static org.graylog2.log4j2.GelfAppender org.graylog2.log4j2.GelfAppender.createGelfAppender(org.apache.logging.log4j.core.Filter,org.apache.logging.log4j.core.Layout,java.lang.String,java.lang.Boolean,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean,java.lang.String).
2015-11-26 11:45:04,311 main DEBUG Calling createGelfAppender on class org.graylog2.log4j2.GelfAppender for element GELF with params(null, null, name="GELFAppender", ignoreExceptions="true", server="127.0.0.1", port="12201", protocol="UDP", hostName="example.org", queueSize="512", connectTimeout="1000", reconnectDelay="500", sendBufferSize="-1", tcpNoDelay="false", tcpKeepAlive="false", includeSource="true", includeThreadContext="true", includeStackTrace="true", additionalFields="null")
```

**Comment by joschi** [comment]
If you could provide a reproducible test case, we'll reopen this issue.

**Comment by delfer** [comment]
I've found my error.
I call "LogManager.getLogger" in my handmade library, but log4j2 core and log4j2.xml appear in main project.
When I've added log4j2-gelf JAR into "my handmade library" its start working.
Thank you.

**Comment by aminkhodamoradi** [comment]
this is my log4j2.xml Configuration:

```
<Configuration status="WARN" packages="org.graylog2.log4j2">
    <Appenders>

     <Console name="Console" target="SYSTEM_OUT">
        <PatternLayout pattern="%d{dd.MM.yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
     </Console>

    <GELF name="GELFAppender" server="192.168.248.128" port="12201" hostName="ddocserver">
    </GELF>

</Appenders>
<Loggers>
    <Root level="warn">
        <AppenderRef ref="Console"/>
        <AppenderRef ref="GELFAppender"/>
    </Root>
</Loggers>
```

</Configuration>

and this dependencies:

```
      <dependency>
        <groupId>org.graylog2.log4j2</groupId>
        <artifactId>log4j2-gelf</artifactId>
        <version>1.1.0</version>
    </dependency> 
     <dependency>
        <groupId>org.apache.logging.log4j</groupId>
        <artifactId>log4j-1.2-api</artifactId>
        <version>2.6.1</version>
        <type>jar</type>
    </dependency>
```

but I got many errors and no log in console or graylog! please help mee.

> ERROR StatusLogger Unrecognized format specifier [d]
> ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [thread]
> ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [level]
> ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [logger]
> ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [msg]
> ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [n]
> ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
> ERROR StatusLogger Unrecognized format specifier [d]
> ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [thread]
> ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [level]
> ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [logger]
> ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [msg]
> ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
> ERROR StatusLogger Unrecognized format specifier [n]
> ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
> %d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%n[INFO] NETBEANS-ExecEvent:{"mojo":{"impl":"org.codehaus.mojo.exec.ExecMojo","urls":["file:\/C:\/Users\/AminK\/.m2\/repository\/org\/codehaus\/mojo\/exec-maven-plugin\/1.2.1\/exec-maven-plugin-1.2.1.jar","file:\/C:\/Users\/AminK\/.m2\/repository\/org\/apache\/maven\/reporting\/maven-reporting-api\/2.0.6\/maven-reporting-api-2.0.6.jar","file:\/C:\/Users\/AminK\/.m2\/repository\/org\/apache\/maven\/doxia\/doxia-sink-api\/1.0-alpha-7\/doxia-sink-api-1.0-alpha-7.jar","file:\/C:\/Users\/AminK\/.m2\/repository\/commons-cli\/commons-cli\/1.0\/commons-cli-1.0.jar","file:\/C:\/Users\/AminK\/.m2\/repository\/org\/codehaus\/plexus\/plexus-interactivity-api\/1.0-alpha-4\/plexus-interactivity-api-1.0-alpha-4.jar","file:\/C:\/Users\/AminK\/.m2\/repository\/org\/codehaus\/plexus\/plexus-utils\/2.0.5\/plexus-utils-2.0.5.jar","file:\/C:\/Users\/AminK\/.m2\/repository\/org\/apache\/commons\/commons-exec\/1.1\/commons-exec-1.1.jar"],"goal":"exec","id":"org.codehaus.mojo:exec-maven-plugin:1.2.1","source":"CLI","execId":"default-cli"},"type":"MojoSucceeded"}

**Comment by sirolf2009** [comment]
```log4j-1.2-api``` is a dependency that acts as a bridge from log4j to log4j2. Which means that you have the GELF logger and the bridge, but you're still missing the actual log4j2 dependency. Try adding
```xml
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.8.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.8.2</version>
        </dependency>
```
