### ISSUE TITLE
DEF: protocol TCP causing locking of appender thread

### ISSUE THREAD

**Issue by tibormucha** [Graylog2/log4j2-gelf#15]
In use case, when current TCP connection is dropped (f.e. firewall)

> org.graylog2.gelfclient.encoder.GelfMessageJsonEncoder - JSON encoding error
> java.io.IOException: An existing connection was forcibly closed by the remote host 

then the gelfTcpTranspor tread is blocking each appender thread with  queue.put(message)

```
   public void send(final GelfMessage message) throws InterruptedException {
        LOG.debug("Sending message: {}", message.toString());
        queue.put(message);
    }
```

**EXPECTED**
the appender thread will not be blocked by transport thread .

**Comment by louxiu** [comment]
I think we should use the `trySend` instead of `send`.
