### ISSUE TITLE
performance concern with current includeSource implementation

### ISSUE THREAD

**Issue by bill-okara** [Graylog2/log4j2-gelf#19]
In current implementation:

```
public void append(LogEvent event) {
...
    final StackTraceElement source = event.getSource();
    if (includeSource && source != null) {    
        builder.additionalField("sourceFileName", source.getFileName());
```

The problem is that the event.getSource() is part of the location information that could have a performance impact according to the log4j2 [doc](https://logging.apache.org/log4j/2.x/manual/layouts.html#LocationInformation): 

> If one of the layouts is configured with a location-related attribute like HTML locationInfo, or one of the patterns %C or %class, %F or %file, %l or %location, %L or %line, %M or %method, Log4j will take a snapshot of the stack, and walk the stack trace to find the location information.
> 
> This is an expensive operation: 1.3 - 5 times slower for synchronous loggers...

Should the includeSource be checked first before doing the event.getSource? like:

```
if (includeSource) {
    final StackTraceElement source = event.getSource();
    if (source != null) {
            builder.additionalField("sourceFileName", source.getFileName());
           ...
```

Thanks,
Bill

**Comment by joschi** [comment]
@bill-okara Do you have any benchmarks for this use case?

**Comment by bill-okara** [comment]
no, I didn't have any benchmarks. But by looking at log4j2 LogEvent.getSource code, the implementation seems to match what's mentioned in the location related doc regarding the performance concern of taking a snapshot of the stack:

```
    public StackTraceElement getSource() {
        ...
        source = calcLocation(loggerFqcn);
        return source;
    }

    public static StackTraceElement calcLocation(final String fqcnOfLogger) {
        ...
        final StackTraceElement[] stackTrace = new Throwable().getStackTrace();
```

So it seems reasonable to avoid the overhead of getting and parsing the stack if includeSource is false?

Thanks,
Bill

**Comment by joschi** [comment]
@bill-okara Thanks for digging into this!

**Comment by bill-okara** [comment]
@joschi, thanks for the fix!

-Bill
