### ISSUE TITLE
Log4j2 Lookups don't work

### ISSUE THREAD

**Issue by Orxcle-xx** [Graylog2/log4j2-gelf#20]
Hi guys,

First of of all, thanks for the useful plugin. I've tried to use it and seems it works very well.

Unfortunately, "additionalFields" don't work with the Log4j2 Lookups as is written in description
( I tried to use "${ctx:userId}" what I've put in ThreadContext ).

I also think that it would be great if Log4j2 Lookups could be used for "hostName" parameter.
In cloud architecture you might create one build or image and then run it on different hosts, so for sure "hostName" should be somewhat dynamic.

What do you think?

Best Regards,
Maksim

**Comment by joschi** [comment]
@Orxcle-xx I cannot reproduce your issues.

Using the sample project at https://github.com/joschi/log4j2-gelf-issue-20, the property lookup is working exactly as it should (including the `server` and `port` configuration settings).

This is the raw GELF message (beautified JSON for readability) I've received using the mentioned sample project:

``` json
{
   "_sourceClassName" : "org.example.Main",
   "_loggerName" : "HelloWorld",
   "_sourceMethodName" : "main",
   "_threadName" : "main",
   "short_message" : "Hello, World!",
   "_sourceLineNumber" : 13,
   "_contextStack" : "[Test]",
   "host" : "example.org",
   "timestamp" : 1472045926.748,
   "version" : "1.1",
   "_sourceFileName" : "Main.java",
   "_jvm" : "1.8.0_102",
   "level" : 6,
   "_test" : "foobar"
}
```
