### ISSUE TITLE
Question about additional fields in code

### ISSUE THREAD

**Issue by andrasnemes** [Graylog2/log4j2-gelf#21]
Hello,

We're using this library with log4j2 to send gelf messages to Graylog and it works fine. I have a question about additional fields. 

I'm adding a couple of hard-coded additional fields via the XML configuration file, like environment = alpha. Is there a way to add these fields in code? We have a number of dynamic fields that we would like to set during runtime. In one project I solved this by using the objects in the org.graylog2 library such as GelfMessage:

```
GelfMessage gelfMessage = new GelfMessage();
Map<String, Object> additionalParameters = new Hashtable<String, Object>();
additionalParameters.put("referrer", referrer);
additionalParameters.put("duration_ms", duration);
...
...
gelfMessage.setAdditonalFields(additionalParameters);
```

However, this meant bypassing log4j which defeated the purpose of using a logging framework.

Is there a way to inject these additional fields into the gelf message dynamically via log4j2 library?

Thanks for your help,
Andras

**Comment by joschi** [comment]
@andrasnemes You can simply use the [Log4j 2 Thread Context](https://logging.apache.org/log4j/2.x/manual/thread-context.html) for this.
