### ISSUE TITLE
Source field

### ISSUE THREAD

**Issue by burberius** [Graylog2/log4j2-gelf#23]
I noticed the source field only shows the hostname, is that the correct behavior? Or a bug?
I would expect the fqdn as source.

**Comment by joschi** [comment]
@burberius Yes, that's the intended behavior. You can override the host name using the `hostName` setting.

**Comment by burberius** [comment]
But then I need a specific configuration for each host. :-(
Perhaps I will provide a merge request with some switch to get the fqdn as source.
I'm used to that behavior from logback-gelf. It's very useful if you have dev, test and production systems in different nets specified by different subdomain like: frontend.dev.company.com + frontend.test.company.com

**Comment by burberius** [comment]
Now I started my code on two different machines, one delivers the hostname as source and the other the fqdn.
I think it's the same problem, I fixed some time ago for logback-gelf:
https://github.com/Moocar/logback-gelf/pull/32
https://github.com/Moocar/logback-gelf/commit/f6fe635bb91950165fffb745a1142c02a885c542
