### ISSUE TITLE
Unable to send log with log4j-core 2.7 and log4j-slf4j-impl 2.7

### ISSUE THREAD

**Issue by wilvh** [Graylog2/log4j2-gelf#26]
Hi,

I'm unable to send log to Graylog 2.1.2 with log4j2-gelf 1.3.1, log4j-core 2.7 and log4j-slf4j-impl 2.7.
No exception is thrown and no packet is sent on the network.

I've attached a log file from log4j2.

Thank you,

[logGelf.txt](https://github.com/Graylog2/log4j2-gelf/files/592447/logGelf.txt)

**Comment by joschi** [comment]
@wilvh Please attach a minimal example application to reproduce the problem, including your log4j2 configuration.

**Comment by wilvh** [comment]
@joschi Here is a simple example of an application that works in 2.6.2 but not in 2.6.7

[log4j2.txt](https://github.com/Graylog2/log4j2-gelf/files/594016/log4j2.txt)
[Main.txt](https://github.com/Graylog2/log4j2-gelf/files/594017/Main.txt)

**Comment by joschi** [comment]
@wilvh I couldn't reproduce any problem with log4j 2.7, but your example application simply exits too fast for the GELF appender to send its contents to Graylog.

Try the following in your example application:

``` java
package com.example;

public class   Main {
  private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(Main.class);
  public static void main(String[] args) throws InterruptedException {
    log.error("SEVERE ERROR...");
    System.out.println("END");
    Thread.sleep(1000L);
  }
}
```

**Comment by wilvh** [comment]
@joschi Thank you for your fast reply. I've tried your example and it works with log4j 2.7. 
In 2.6.2 I had some logs that had not registered in Graylog and your solution seems to have fixed this problem too. Is there another method than adding a Thread.sleep in all my programs? (Do not exit the program before GELF appender has sent its content). Thank you very much
