### ISSUE TITLE
Disable automatic MDC field creation

### ISSUE THREAD

**Issue by szerhusenBC** [Graylog2/log4j2-gelf#30]
Hi,

I have a problem with this appender. I created the following appender configuration:

`
<GELF name="gelfAppender" server="XXX.XXX.XXX.XXX" port="XXX" hostName="myHost">
         <PatternLayout pattern="%msg%n"/>
         
         <KeyValuePair key="Sourcename" value="mySourceName"/>
         <KeyValuePair key="Class" value="Application"/>
         <KeyValuePair key="Vendor" value="myVendor"/>
         <KeyValuePair key="APP_Name" value="myAppName"/>
         <KeyValuePair key="APP_Stage" value="myStage"/>
      </GELF>
`

In the application some MDC fields are set. Now I see in Graylog that all MDC fields have automatically been created in the DB. Is there a possibility to disabled that? In your documentation I don't see an attribute for that.

There is a project under https://github.com/mp911de/logstash-gelf that offers an attribute "IncludeFullMdc" for that.

**Comment by joschi** [comment]
@szerhusenBC In Log4j 2.x, the old MDC is called [ThreadContext](https://logging.apache.org/log4j/2.x/manual/thread-context.html), and the respective setting for this appender is `includeThreadContext`.

**Comment by szerhusenBC** [comment]
Thank you for the fast response!
